#!/bin/sh
set -e

. ./PACKAGE.FS

tar cfJv python-lhafile-$PACKAGE_VERSION.tar.xz \
	COPYING.txt \
	debian/changelog \
	debian/source \
	debian/source/format \
	debian/.gitignore \
	debian/rules \
	debian/copyright \
	debian/control \
	MANIFEST.in \
	README.md \
	python-lhafile.spec \
	setup.py \
	lzhlib.c \
	lhafile/lhafile.py \
	lhafile/tests/archive_lhaca.lzh \
	lhafile/tests/test_lhafile.py \
	lhafile/tests/archive_lhaunix_lh5.lzh \
	lhafile/tests/archive_lhaunix_lh7.lzh \
	lhafile/tests/archive_lhaunix_lh6.lzh \
	lhafile/tests/archive_lhaplus.lzh \
	lhafile/__init__.py
